import React, { useState } from 'react';
import { View, Text, StyleSheet, Pressable, ScrollView, TextInput, Switch, Platform } from 'react-native';
import { router } from 'expo-router';
import { useStore } from '../store/useStore';
import { WorkBreakCard } from '../components/WorkBreakCard';
import { Nimbo } from '../components/Nimbo';
import { validateSchedule, currentShift, nextShift, WorkSchedule, CoachStyle } from '../services/workCore';
import { requestWorkPermission, syncWorkNotifications } from '../services/workNotifications';

const dayNames=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];
const modes:[WorkSchedule['mode'],string][]=[['midpoint','Mid-shift only'],['120','Every 2 hours'],['180','Every 3 hours'],['custom','Custom interval'],['off','Off']];
export default function WorkScreen() {
  const saved=useStore(s=>s.work.schedule),profile=useStore(s=>s.profile);
  const [draft,setDraft]=useState<WorkSchedule>(saved),[custom,setCustom]=useState(String(saved.interval)),[message,setMessage]=useState(''),[error,setError]=useState('');
  const patch=(updates:Partial<WorkSchedule>)=>setDraft({...draft,...updates});
  let preview='Choose your working days to see the automatic midpoint.';
  try{if(draft.days.length){const valid=validateSchedule({...draft,interval:Number(custom)});const shift=currentShift(valid)||nextShift(valid);if(shift)preview=`${new Date(shift.start).toLocaleString([], {weekday:'short',hour:'numeric',minute:'2-digit'})} → ${new Date(shift.end).toLocaleString([], {weekday:'short',hour:'numeric',minute:'2-digit'})}\n${shift.minutes/60} hours · Midpoint ${new Date(shift.midpoint).toLocaleString([], {weekday:'short',hour:'numeric',minute:'2-digit'})}`;}}catch{preview='Enter valid HH:MM times and choose at least one workday.';}
  const save=()=>{try{const schedule=validateSchedule({...draft,interval:draft.mode==='custom'?Number(custom):saved.interval});const state=useStore.getState();const work=JSON.parse(JSON.stringify(state.work));work.schedule=schedule;for(const shift of Object.values(work.runtime.shifts) as {slots:Record<string,{status:string}>}[])for(const slot of Object.values(shift.slots))if(['offered','snoozed'].includes(slot.status))slot.status='missed';state.setWork(work);state.updateProfile({shiftStart:schedule.start,shiftEnd:schedule.end});setDraft(schedule);setError('');setMessage('Saved. Nimbo will follow your working rhythm.');void syncWorkNotifications().catch(()=>setError('Schedule saved; device notifications could not be updated.'));}catch(err){setError((err as Error).message);setMessage('');}};
  const permit=async()=>{try{const allowed=await requestWorkPermission();setMessage(allowed?'Permission granted. Turn on notifications and save your schedule.':'In-app reminders still work without permission.');await syncWorkNotifications();}catch{setMessage('Notifications are unavailable here. In-app reminders still work.');}};
  return <ScrollView contentContainerStyle={styles.container} keyboardShouldPersistTaps="handled"><Pressable accessibilityRole="button" accessibilityLabel="Back to Home" onPress={()=>router.replace('/')}><Text style={styles.back}>← Back to Home</Text></Pressable><Text accessibilityRole="header" style={styles.header}>Work Schedule</Text><Text style={styles.sub}>A little reset, with Nimbo. Optional, on your terms.</Text><Nimbo/><WorkBreakCard/>
    <View style={styles.card}><View style={styles.row}><Text style={styles.title}>Help me take breaks during work</Text><Switch accessibilityLabel="Help me take breaks during work" value={draft.enabled} onValueChange={enabled=>patch({enabled})} trackColor={{true:'#a78bfa'}}/></View>
    {draft.enabled&&<><Text style={styles.label}>Work start time · HH:MM</Text><TextInput accessibilityLabel="Work start time" style={styles.input} value={draft.start} onChangeText={start=>patch({start})} placeholder="09:00" maxLength={5} autoCapitalize="none"/>
    <Text style={styles.label}>Work end time · HH:MM</Text><TextInput accessibilityLabel="Work end time" style={styles.input} value={draft.end} onChangeText={end=>patch({end})} placeholder="17:00" maxLength={5}/>
    <Text style={styles.label}>Working days · when your shift starts</Text><View style={styles.options}>{[1,2,3,4,5,6,0].map(d=><Pressable key={d} accessibilityRole="checkbox" accessibilityLabel={['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'][d]} accessibilityState={{checked:draft.days.includes(d)}} onPress={()=>patch({days:draft.days.includes(d)?draft.days.filter(x=>x!==d):[...draft.days,d]})} style={[styles.chip,draft.days.includes(d)&&styles.selected]}><Text style={draft.days.includes(d)?styles.chosen:styles.option}>{dayNames[d]}</Text></Pressable>)}</View><Text style={styles.note}>A Monday 22:00–06:00 shift ends Tuesday. Times follow this device’s timezone: {Intl.DateTimeFormat().resolvedOptions().timeZone}.</Text>
    <Text style={styles.label}>Preferred break</Text><View style={styles.options}>{([5,10] as const).map(minutes=><Pressable key={minutes} accessibilityRole="button" accessibilityLabel={`Prefer ${minutes} minutes`} accessibilityState={{selected:draft.minutes===minutes}} onPress={()=>patch({minutes})} style={[styles.chip,draft.minutes===minutes&&styles.selected]}><Text style={draft.minutes===minutes?styles.chosen:styles.option}>{minutes} minutes</Text></Pressable>)}</View>
    <Text style={styles.label}>Break reminders</Text><View style={styles.options}>{modes.map(([mode,label])=><Pressable key={mode} accessibilityRole="button" accessibilityState={{selected:draft.mode===mode}} onPress={()=>patch({mode})} style={[styles.chip,draft.mode===mode&&styles.selected]}><Text style={draft.mode===mode?styles.chosen:styles.option}>{label}</Text></Pressable>)}</View>{draft.mode==='custom'&&<><Text style={styles.label}>Custom interval · 30–720 minutes</Text><TextInput accessibilityLabel="Custom interval" style={styles.input} value={custom} onChangeText={setCustom} keyboardType="number-pad"/></>}
    <Text style={styles.preview}>{preview}</Text><View style={styles.row}><Text style={styles.title}>Optional device notifications</Text><Switch accessibilityLabel="Optional device notifications" value={draft.desktop} onValueChange={desktop=>patch({desktop})}/></View><Pressable accessibilityRole="button" onPress={permit} style={styles.secondary}><Text style={styles.option}>Allow notifications</Text></Pressable><Text style={styles.note}>{Platform.OS==='web'?'Web preview reminders need the app open. Browsers may suspend background timers.':'Native local notifications are scheduled for the next week (up to 48); reopen regularly to refresh. Device settings may delay delivery.'} Notifications show Nimbo’s name and break message. Permission is optional.</Text></>}
    {!!error&&<Text accessibilityRole="alert" style={styles.error}>{error}</Text>}{!!message&&<Text accessibilityLiveRegion="polite" style={styles.note}>{message}</Text>}<Pressable accessibilityRole="button" onPress={save} style={styles.button}><Text style={styles.buttonText}>Save work schedule</Text></Pressable></View>
    <View style={styles.card}><Text style={styles.title}>Nimbo’s communication style</Text><Text style={styles.note}>The wording changes; the optional five- or ten-minute recommendation stays the same.</Text><View style={styles.options}>{(['Supportive','Calm','Motivational','Funny','Direct'] as CoachStyle[]).map(coachStyle=><Pressable key={coachStyle} accessibilityRole="button" accessibilityState={{selected:(profile.coachStyle||'Supportive')===coachStyle}} onPress={()=>useStore.getState().updateProfile({coachStyle})} style={[styles.chip,(profile.coachStyle||'Supportive')===coachStyle&&styles.selected]}><Text style={(profile.coachStyle||'Supportive')===coachStyle?styles.chosen:styles.option}>{coachStyle}</Text></Pressable>)}</View></View>
  </ScrollView>;
}
const styles=StyleSheet.create({container:{flexGrow:1,backgroundColor:'#f8fafc',padding:20,paddingTop:50,paddingBottom:40},header:{fontSize:28,fontWeight:'700',color:'#1e293b',marginTop:20,marginBottom:8},sub:{fontSize:14,color:'#64748b',lineHeight:22},back:{color:'#7c3aed',fontSize:15,paddingVertical:10},card:{backgroundColor:'white',borderRadius:18,padding:20,marginBottom:20},row:{flexDirection:'row',alignItems:'center',gap:10,justifyContent:'space-between',marginBottom:12},title:{fontSize:16,fontWeight:'600',color:'#334155',flexShrink:1},label:{fontSize:13,fontWeight:'600',color:'#475569',marginTop:18,marginBottom:8},input:{backgroundColor:'#f1f5f9',borderRadius:10,padding:14,fontSize:16,color:'#1e293b'},options:{flexDirection:'row',flexWrap:'wrap',gap:8},chip:{borderRadius:12,minHeight:44,padding:12,backgroundColor:'#f1f5f9'},selected:{backgroundColor:'#8b5cf6'},chosen:{color:'white',fontWeight:'600',fontSize:13},option:{color:'#5b21b6',fontSize:13,fontWeight:'600'},note:{fontSize:12,color:'#64748b',lineHeight:20,marginVertical:12},preview:{backgroundColor:'#ede9fe',color:'#5b21b6',padding:15,borderRadius:12,lineHeight:22,marginVertical:20},button:{backgroundColor:'#8b5cf6',padding:16,borderRadius:12,alignItems:'center'},buttonText:{color:'white',fontWeight:'700'},secondary:{padding:14,borderRadius:12,backgroundColor:'#ede9fe',alignSelf:'flex-start'},error:{color:'#b91c1c',marginVertical:12}});
