import assert from 'node:assert/strict';
import * as W from '../services/workCore';
const C={newState:():{profile?:unknown;food:number;work?:W.WorkState}=>({food:0}),reward:(s:{food:number},_:string)=>{s.food+=2;}};
const at=(date:number,h:number,m=0)=>new Date(2026,9,date,h,m);
const setup=(changes:Partial<W.WorkSchedule>={})=>{const w=W.defaultWork();w.schedule={...w.schedule,enabled:true,days:[0,1,2,3,4,5,6],...changes};return w;};
test('day shift midpoint is 1 PM without user calculation',()=>{const shift=W.shiftOn(setup().schedule,at(4,0))!;assert.equal(shift.minutes,480);assert.equal(new Date(shift.midpoint).getHours(),13);});
test('night shift crosses midnight and belongs to its start weekday',()=>{const w=setup({start:'22:00',end:'06:00',days:[1]});const shift=W.currentShift(w.schedule,at(6,2))!;assert.equal(shift.minutes,480);assert.equal(new Date(shift.start).getDate(),5);assert.equal(new Date(shift.midpoint).getHours(),2);assert.equal(W.currentShift(w.schedule,at(6,6)),null);assert.equal(W.currentShift(w.schedule,at(7,2)),null);});
test('arbitrary working days and off days',()=>{const w=setup({days:[0,4]});assert.ok(W.currentShift(w.schedule,at(4,10)));assert.equal(W.currentShift(w.schedule,at(5,10)),null);assert.equal(new Date(W.nextShift(w.schedule,at(5,10))!.start).getDay(),4);});
test('custom-date adapter supports rotating shifts and off overrides',()=>{const w=setup({overrides:{'2026-10-04':{start:'12:00',end:'20:00'},'2026-10-05':{off:true}}});assert.equal(new Date(W.shiftOn(w.schedule,at(4,0))!.midpoint).getHours(),16);assert.equal(W.shiftOn(w.schedule,at(5,0)),null);});
test('default is opt-in and quiet, migration preserves all existing app fields',()=>{const s=C.newState();s.profile={petName:'Nori',style:'Funny'};C.reward(s,'sleep');const existing=JSON.parse(JSON.stringify(s));const w=W.migrateWork(s);assert.equal(w.schedule.enabled,false);assert.deepEqual(w.schedule.days,[]);assert.equal(w.schedule.mode,'midpoint');delete s.work;assert.deepEqual(s,existing);});
test('equal times and invalid schedules rejected',()=>{assert.throws(()=>W.validateSchedule(setup({end:'09:00'}).schedule));assert.throws(()=>W.validateSchedule(setup({days:[]}).schedule));assert.throws(()=>W.validateSchedule(setup({interval:5}).schedule));assert.throws(()=>W.validateSchedule(setup({start:'99:01'}).schedule));assert.equal(W.validateSchedule(setup({days:[0,0,6]}).schedule).days.length,2);});
test('frequencies stay inside the shift and include no duplicate midpoint',()=>{const w=setup({mode:'120'});let slots=W.slotsFor(w.schedule,W.shiftOn(w.schedule,at(4,0)));assert.deepEqual(slots.map(x=>new Date(x.at).getHours()),[11,13,15]);w.schedule.mode='180';slots=W.slotsFor(w.schedule,W.shiftOn(w.schedule,at(4,0)));assert.deepEqual(slots.map(x=>new Date(x.at).getHours()),[12,15]);w.schedule.mode='custom';w.schedule.interval=60;assert.equal(W.slotsFor(w.schedule,W.shiftOn(w.schedule,at(4,0))).length,7);w.schedule.mode='off';assert.deepEqual(W.slotsFor(w.schedule,W.shiftOn(w.schedule,at(4,0))),[]);});
test('once-only reminder markers survive a serialized reload',()=>{let w=setup();assert.equal(W.advanceWork(w,at(4,12,59)).notices.length,0);assert.equal(W.advanceWork(w,at(4,13)).notices.length,1);w=JSON.parse(JSON.stringify(w));assert.equal(W.advanceWork(w,at(4,13,1)).notices.length,0);assert.ok(W.offeredBreak(w,at(4,13,1)));});
test('sleep, pause, disable, off and outside shift suppress delivery',()=>{for(const change of ['sleep','pause','disable','off']){const w=setup();if(change==='pause')w.runtime.paused=true;if(change==='disable')w.schedule.enabled=false;if(change==='off')w.schedule.mode='off';assert.equal(W.advanceWork(w,at(4,13),change==='sleep').notices.length,0);assert.equal(W.offeredBreak(w,at(4,13),change==='sleep'),null);}assert.equal(W.advanceWork(setup(),at(4,17)).notices.length,0);});
test('sleeping across midpoint does not create a catch-up alert on wake',()=>{const w=setup();W.advanceWork(w,at(4,13),true);assert.equal(W.advanceWork(w,at(4,13,10)).notices.length,0);assert.equal(W.offeredBreak(w,at(4,13,10)),null);});
test('skip and finished workday suppress entire overnight shift, not next one',()=>{for(const action of ['skip','finish'] as const){const w=setup({start:'22:00',end:'06:00'});W.workAction(w,action,at(4,23));assert.equal(W.advanceWork(w,at(5,2)).notices.length,0);assert.equal(W.advanceWork(w,at(6,2)).notices.length,1);}});
test('pause clears an outstanding reminder and resume preserves the decision',()=>{const w=setup();W.advanceWork(w,at(4,13));W.workAction(w,'pause',at(4,13));assert.equal(W.offeredBreak(w,at(4,13)),null);W.workAction(w,'resume',at(4,13,5));assert.equal(W.advanceWork(w,at(4,13,5)).notices.length,0);});
test('snooze delivers once after fifteen minutes and never after shift end',()=>{const w=setup();W.advanceWork(w,at(4,13));const slot=W.offeredBreak(w,at(4,13))!;W.workAction(w,'snooze',at(4,13),{slotId:slot.id});assert.equal(W.advanceWork(w,at(4,13,14)).notices.length,0);assert.equal(W.advanceWork(w,at(4,13,15)).notices.length,1);assert.equal(W.advanceWork(w,at(4,13,16)).notices.length,0);W.workAction(w,'snooze',at(4,16,59),{slotId:slot.id});assert.equal(W.advanceWork(w,at(4,17,14)).notices.length,0);});
test('five and ten minute timers survive reload, complete once, and block repeat breaks',()=>{for(const minutes of [5,10]){let w=setup();W.advanceWork(w,at(4,13));const slot=W.offeredBreak(w,at(4,13))!;W.workAction(w,'take',at(4,13),{minutes,slotId:slot.id});assert.throws(()=>W.workAction(w,'take',at(4,13),{minutes,slotId:slot.id}));w=JSON.parse(JSON.stringify(w));assert.equal(W.advanceWork(w,at(4,13,minutes-1)).notices.length,0);assert.equal(W.advanceWork(w,at(4,13,minutes)).notices[0].kind,'completion');assert.equal(w.runtime.timer,null);assert.equal(W.advanceWork(w,at(4,13,minutes+1)).notices.length,0);assert.equal(W.offeredBreak(w,at(4,13,minutes+1)),null);W.workAction(w,'dismiss',at(4,13,minutes+1));assert.equal(w.runtime.completion,null);}});
test('completion is silent during sleep, when finished, and when disabled',()=>{for(const change of ['sleep','finish','disable']){const w=setup();W.advanceWork(w,at(4,13));const slot=W.offeredBreak(w,at(4,13))!;W.workAction(w,'take',at(4,13),{minutes:5,slotId:slot.id});if(change==='finish')W.workAction(w,'finish',at(4,13,1));if(change==='disable')w.schedule.enabled=false;assert.equal(W.advanceWork(w,at(4,13,5),change==='sleep').notices.length,0);assert.ok(w.runtime.completion);}});
test('late reopening coalesces missed intervals and never sends a backlog',()=>{const w=setup({mode:'120'});assert.equal(W.advanceWork(w,at(4,15,10)).notices.length,1);assert.equal(W.offeredBreak(w,at(4,15,10))!.at,W.slotsFor(w.schedule,W.currentShift(w.schedule,at(4,15,10))).at(-1)!.at);assert.equal(W.advanceWork(setup(),at(4,14)).notices.length,0);});
test('a new interval replaces an ignored old offer instead of stacking prompts',()=>{const w=setup({mode:'120'});W.advanceWork(w,at(4,11));assert.equal(W.advanceWork(w,at(4,13)).notices.length,1);const offered=Object.values(w.runtime.shifts['2026-10-04'].slots).filter(x=>x.status==='offered');assert.equal(offered.length,1);});
test('snooze is respected even when another interval becomes due',()=>{const w=setup({mode:'custom',interval:30});W.advanceWork(w,at(4,9,30));const slot=W.offeredBreak(w,at(4,9,30))!;W.workAction(w,'snooze',at(4,9,59),{slotId:slot.id});assert.equal(W.advanceWork(w,at(4,10)).notices.length,0);assert.equal(W.advanceWork(w,at(4,10,14)).notices.length,1);});
test('all five personalities retain the same break duration and optional choice',()=>{for(const style of ['Supportive','Calm','Motivational','Funny','Direct'] as const){const text=W.reminderText(style,10);assert.match(text,/take 10 minutes/);assert.match(text,/If your work allows/);assert.doesNotMatch(text,/abandon|lazy|resignation|GET BACK/i);}});
test('DST uses actual elapsed shift length with a midpoint between its instants',()=>{
  const previous=process.env.TZ;process.env.TZ='America/New_York';
  try{const w=setup({start:'22:00',end:'06:00'});const fall=W.shiftOn(w.schedule,new Date(2026,9,31))!;const spring=W.shiftOn(w.schedule,new Date(2026,2,7))!;assert.equal(fall.minutes,540);assert.equal(spring.minutes,420);for(const shift of [fall,spring])assert.equal(Date.parse(shift.midpoint)-Date.parse(shift.start),Date.parse(shift.end)-Date.parse(shift.midpoint));}
  finally{if(previous===undefined)delete process.env.TZ;else process.env.TZ=previous;}
});
