import type { NimboState } from '../services/nimboStateController';
export type NimboAssetKey='BREAK_TIME'|'EATING'|'ENERGETIC'|'HAPPY'|'IMPROVING'|'NEUTRAL'|'SLEEPING'|'STRESSED'|'TIRED';
const keys:Record<NimboState,NimboAssetKey>={NEUTRAL:'NEUTRAL',HAPPY:'HAPPY',ENERGETIC:'ENERGETIC',CALM:'NEUTRAL',SLEEPY:'TIRED',TIRED:'TIRED',STRESSED:'STRESSED',ENCOURAGING:'NEUTRAL',SLEEPING:'SLEEPING',WAKING:'NEUTRAL',EATING:'EATING',PLAYING:'NEUTRAL',CELEBRATING:'ENERGETIC',BREAK_TIME:'BREAK_TIME',IMPROVING:'IMPROVING'};
export const getNimboAssetKey=(state:NimboState):NimboAssetKey=>keys[state]||'NEUTRAL';
